//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ach.forest_shuffle.mobile_app.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LivingOrganisms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LivingOrganisms() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ach.forest_shuffle.mobile_app.Resources.Strings.LivingOrganisms", typeof(LivingOrganisms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alpine Marmot.
        /// </summary>
        internal static string AlpineMarmot {
            get {
                return ResourceManager.GetString("AlpineMarmot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alpine Newt.
        /// </summary>
        internal static string AlpineNewt {
            get {
                return ResourceManager.GetString("AlpineNewt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barbastelle Bat.
        /// </summary>
        internal static string BarbastelleBat {
            get {
                return ResourceManager.GetString("BarbastelleBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barn Owl.
        /// </summary>
        internal static string BarnOwl {
            get {
                return ResourceManager.GetString("BarnOwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bearded Vulpture.
        /// </summary>
        internal static string BeardedVulpture {
            get {
                return ResourceManager.GetString("BeardedVulpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bechstein&apos;s Bat.
        /// </summary>
        internal static string BechsteinsBat {
            get {
                return ResourceManager.GetString("BechsteinsBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beech.
        /// </summary>
        internal static string Beech {
            get {
                return ResourceManager.GetString("Beech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beech Marten.
        /// </summary>
        internal static string BeechMarten {
            get {
                return ResourceManager.GetString("BeechMarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bee Swarm.
        /// </summary>
        internal static string BeeSwarm {
            get {
                return ResourceManager.GetString("BeeSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birch.
        /// </summary>
        internal static string Birch {
            get {
                return ResourceManager.GetString("Birch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blackberries.
        /// </summary>
        internal static string Blackberries {
            get {
                return ResourceManager.GetString("Blackberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blackthorn.
        /// </summary>
        internal static string Blackthorn {
            get {
                return ResourceManager.GetString("Blackthorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Black Trumpet.
        /// </summary>
        internal static string BlackTrumpet {
            get {
                return ResourceManager.GetString("BlackTrumpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blueberry.
        /// </summary>
        internal static string Blueberry {
            get {
                return ResourceManager.GetString("Blueberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brown Bear.
        /// </summary>
        internal static string BrownBear {
            get {
                return ResourceManager.GetString("BrownBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brown Long-Eared Bat.
        /// </summary>
        internal static string BrownLongEaredBat {
            get {
                return ResourceManager.GetString("BrownLongEaredBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bullfinch.
        /// </summary>
        internal static string Bullfinch {
            get {
                return ResourceManager.GetString("Bullfinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camberwell Beauty.
        /// </summary>
        internal static string CamberwellBeauty {
            get {
                return ResourceManager.GetString("CamberwellBeauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capercaillie.
        /// </summary>
        internal static string Capercaillie {
            get {
                return ResourceManager.GetString("Capercaillie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaffinch.
        /// </summary>
        internal static string Chaffinch {
            get {
                return ResourceManager.GetString("Chaffinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chamois.
        /// </summary>
        internal static string Chamois {
            get {
                return ResourceManager.GetString("Chamois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chanterelle.
        /// </summary>
        internal static string Chanterelle {
            get {
                return ResourceManager.GetString("Chanterelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common Hazel.
        /// </summary>
        internal static string CommonHazel {
            get {
                return ResourceManager.GetString("CommonHazel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common Pipistrelle.
        /// </summary>
        internal static string CommonPipistrelle {
            get {
                return ResourceManager.GetString("CommonPipistrelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common Raven.
        /// </summary>
        internal static string CommonRaven {
            get {
                return ResourceManager.GetString("CommonRaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common Toad.
        /// </summary>
        internal static string CommonToad {
            get {
                return ResourceManager.GetString("CommonToad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crane Fly.
        /// </summary>
        internal static string CraneFly {
            get {
                return ResourceManager.GetString("CraneFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digitalis.
        /// </summary>
        internal static string Digitalis {
            get {
                return ResourceManager.GetString("Digitalis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Douglas Fir.
        /// </summary>
        internal static string DouglasFir {
            get {
                return ResourceManager.GetString("DouglasFir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edelweiss.
        /// </summary>
        internal static string Edelweiss {
            get {
                return ResourceManager.GetString("Edelweiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elderberry.
        /// </summary>
        internal static string Elderberry {
            get {
                return ResourceManager.GetString("Elderberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eurasian Jay.
        /// </summary>
        internal static string EurasianJay {
            get {
                return ResourceManager.GetString("EurasianJay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eurasian Magpie.
        /// </summary>
        internal static string EurasianMagpie {
            get {
                return ResourceManager.GetString("EurasianMagpie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Badger.
        /// </summary>
        internal static string EuropeanBadger {
            get {
                return ResourceManager.GetString("EuropeanBadger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Bison.
        /// </summary>
        internal static string EuropeanBison {
            get {
                return ResourceManager.GetString("EuropeanBison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Fat Dormouse.
        /// </summary>
        internal static string EuropeanFatDormouse {
            get {
                return ResourceManager.GetString("EuropeanFatDormouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Hare.
        /// </summary>
        internal static string EuropeanHare {
            get {
                return ResourceManager.GetString("EuropeanHare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Larch.
        /// </summary>
        internal static string EuropeanLarch {
            get {
                return ResourceManager.GetString("EuropeanLarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Polecat.
        /// </summary>
        internal static string EuropeanPolecat {
            get {
                return ResourceManager.GetString("EuropeanPolecat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à European Wildcat.
        /// </summary>
        internal static string EuropeanWildcat {
            get {
                return ResourceManager.GetString("EuropeanWildcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fallow Deer.
        /// </summary>
        internal static string FallowDeer {
            get {
                return ResourceManager.GetString("FallowDeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wild Boar (♀) .
        /// </summary>
        internal static string FemaleWildBoar {
            get {
                return ResourceManager.GetString("FemaleWildBoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fireflies.
        /// </summary>
        internal static string Fireflies {
            get {
                return ResourceManager.GetString("Fireflies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Salamander.
        /// </summary>
        internal static string FireSalamander {
            get {
                return ResourceManager.GetString("FireSalamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fly Agaric.
        /// </summary>
        internal static string FlyAgaric {
            get {
                return ResourceManager.GetString("FlyAgaric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gentian.
        /// </summary>
        internal static string Gentian {
            get {
                return ResourceManager.GetString("Gentian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gnat.
        /// </summary>
        internal static string Gnat {
            get {
                return ResourceManager.GetString("Gnat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Golden Eagle.
        /// </summary>
        internal static string GoldenEagle {
            get {
                return ResourceManager.GetString("GoldenEagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goshawk.
        /// </summary>
        internal static string Goshawk {
            get {
                return ResourceManager.GetString("Goshawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greater Horseshoe Bat.
        /// </summary>
        internal static string GreaterHorseshoeBat {
            get {
                return ResourceManager.GetString("GreaterHorseshoeBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greater Spotted Woodpecker.
        /// </summary>
        internal static string GreaterSpottedWoodpecker {
            get {
                return ResourceManager.GetString("GreaterSpottedWoodpecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Great Green Bush-Cricket.
        /// </summary>
        internal static string GreatGreenBushCricket {
            get {
                return ResourceManager.GetString("GreatGreenBushCricket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hedgehog.
        /// </summary>
        internal static string Hedgehog {
            get {
                return ResourceManager.GetString("Hedgehog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horse Chestnut.
        /// </summary>
        internal static string HorseChestnut {
            get {
                return ResourceManager.GetString("HorseChestnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Large Tortoiseshell.
        /// </summary>
        internal static string LargeTortoiseshell {
            get {
                return ResourceManager.GetString("LargeTortoiseshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linden.
        /// </summary>
        internal static string Linden {
            get {
                return ResourceManager.GetString("Linden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lynx.
        /// </summary>
        internal static string Lynx {
            get {
                return ResourceManager.GetString("Lynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Butterfly.
        /// </summary>
        internal static string MapButterfly {
            get {
                return ResourceManager.GetString("MapButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mole.
        /// </summary>
        internal static string Mole {
            get {
                return ResourceManager.GetString("Mole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moss.
        /// </summary>
        internal static string Moss {
            get {
                return ResourceManager.GetString("Moss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mountain Hare.
        /// </summary>
        internal static string MountainHare {
            get {
                return ResourceManager.GetString("MountainHare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nightingale.
        /// </summary>
        internal static string Nightingale {
            get {
                return ResourceManager.GetString("Nightingale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oak.
        /// </summary>
        internal static string Oak {
            get {
                return ResourceManager.GetString("Oak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parasol Mushroom.
        /// </summary>
        internal static string ParasolMushroom {
            get {
                return ResourceManager.GetString("ParasolMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Peacock Butterfly.
        /// </summary>
        internal static string PeacockButterfly {
            get {
                return ResourceManager.GetString("PeacockButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Penny Bun.
        /// </summary>
        internal static string PennyBun {
            get {
                return ResourceManager.GetString("PennyBun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phoebus Apollo.
        /// </summary>
        internal static string PhoebusApollo {
            get {
                return ResourceManager.GetString("PhoebusApollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pond Turtle.
        /// </summary>
        internal static string PondTurtle {
            get {
                return ResourceManager.GetString("PondTurtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purple Emperor.
        /// </summary>
        internal static string PurpleEmperor {
            get {
                return ResourceManager.GetString("PurpleEmperor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raccoon.
        /// </summary>
        internal static string Raccoon {
            get {
                return ResourceManager.GetString("Raccoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red Deer.
        /// </summary>
        internal static string RedDeer {
            get {
                return ResourceManager.GetString("RedDeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red Fox.
        /// </summary>
        internal static string RedFox {
            get {
                return ResourceManager.GetString("RedFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red Squirrel.
        /// </summary>
        internal static string RedSquirrel {
            get {
                return ResourceManager.GetString("RedSquirrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roe Deer.
        /// </summary>
        internal static string RoeDeer {
            get {
                return ResourceManager.GetString("RoeDeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sapling.
        /// </summary>
        internal static string Sapling {
            get {
                return ResourceManager.GetString("Sapling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Savi&apos;s Pipistrelle.
        /// </summary>
        internal static string SavisPipistrelle {
            get {
                return ResourceManager.GetString("SavisPipistrelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Silver Fir.
        /// </summary>
        internal static string SilverFir {
            get {
                return ResourceManager.GetString("SilverFir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Silver-Washed Fritillary.
        /// </summary>
        internal static string SilverWashedFritillary {
            get {
                return ResourceManager.GetString("SilverWashedFritillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Squeaker.
        /// </summary>
        internal static string Squeaker {
            get {
                return ResourceManager.GetString("Squeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stag Beetle.
        /// </summary>
        internal static string StagBeetle {
            get {
                return ResourceManager.GetString("StagBeetle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steinbock.
        /// </summary>
        internal static string Steinbock {
            get {
                return ResourceManager.GetString("Steinbock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stinging Nettle.
        /// </summary>
        internal static string StingingNettle {
            get {
                return ResourceManager.GetString("StingingNettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stone Pine.
        /// </summary>
        internal static string StonePine {
            get {
                return ResourceManager.GetString("StonePine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sycamore.
        /// </summary>
        internal static string Sycamore {
            get {
                return ResourceManager.GetString("Sycamore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tawny Owl.
        /// </summary>
        internal static string TawnyOwl {
            get {
                return ResourceManager.GetString("TawnyOwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tree Ferns.
        /// </summary>
        internal static string TreeFerns {
            get {
                return ResourceManager.GetString("TreeFerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tree Frog.
        /// </summary>
        internal static string TreeFrog {
            get {
                return ResourceManager.GetString("TreeFrog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violet Carpenter Bee.
        /// </summary>
        internal static string VioletCarpenterBee {
            get {
                return ResourceManager.GetString("VioletCarpenterBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Vole.
        /// </summary>
        internal static string WaterVole {
            get {
                return ResourceManager.GetString("WaterVole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wild Boar.
        /// </summary>
        internal static string WildBoar {
            get {
                return ResourceManager.GetString("WildBoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WildStrawberries.
        /// </summary>
        internal static string WildStrawberries {
            get {
                return ResourceManager.GetString("WildStrawberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wood Ant.
        /// </summary>
        internal static string WoodAnt {
            get {
                return ResourceManager.GetString("WoodAnt", resourceCulture);
            }
        }
    }
}
