namespace Ach.Forest_Shuffle.Domain.Tests.Bdd.Support.Resources;

internal static class LivingOrganismsNameHelper
{   
    internal static Dictionary<string, string> LivingOrganismsFrToTypeDictionnary = new Dictionary<string, string>() { 
        {"Marmotte des Alpes", "AlpineMarmot"},
        {"Triton alpestre", "AlpineNewt"},
        {"Barbastelle d'Europe", "BarbastelleBat"},
        {"Effraie des clochers", "BarnOwl"},
        {"Gypaète barbu", "BeardedVulpture"},
        {"Murin de Bechstein", "BechsteinsBat"},
        {"Hêtre", "Beech"},
        {"Fouine", "BeechMarten"},
        {"Abeille mellifère (essaim)", "BeeSwarm"},
        {"Bouleau", "Birch"},
        {"Mûre", "Blackberries"},
        {"Prunellier", "Blackthorn"},
        {"Trompette de la mort", "BlackTrumpet"},
        {"Myrtille", "Blueberry"},
        {"Ours brun", "BrownBear"},
        {"Oreillard roux", "BrownLongEaredBat"},
        {"Bouvreuil pivoine", "Bullfinch"},
        {"Chêne", "Oak"},
        {"Morio", "CamberwellBeauty"},
        {"Grand tétras", "Capercaillie"},
        {"Pinson des arbres", "Chaffinch"},
        {"Chamois", "Chamois"},
        {"Girolle", "Chanterelle"},
        {"Noisetier commun", "CommonHazel"},
        {"Pipistrelle commune", "CommonPipistrelle"},
        {"Crapaud commun", "CommonToad"},
        {"Tipule", "CraneFly"},
        {"Digitale pourpre", "Digitalis"},
        {"Sapin Douglas", "DouglasFir"},
        {"Edelweiss", "Edelweiss"},
        {"Sureau noir", "Elderberry"},
        {"Geai des chênes", "EurasianJay"},
        {"Pie bavarde", "EurasianMagpie"},
        {"Blaireau européen", "EuropeanBadger"},
        {"Bison d'Europe", "EuropeanBison"},
        {"Loir gris", "EuropeanFatDormouse"},
        {"Lièvre d'Europe", "EuropeanHare"},
        {"Mélèze d'Europe", "EuropeanLarch"},
        {"Putois d'Europe", "EuropeanPolecat"},
        {"Chat forestier", "EuropeanWildcat"},
        {"Daim", "FallowDeer"},
        {"Luciole", "Fireflies"},
        {"Salamandre tachetée", "FireSalamander"},
        {"Amanite tue-mouches", "FlyAgaric"},
        {"Gentiane", "Gentian"},
        {"Moustique", "Gnat"},
        {"Aigle royal", "GoldenEagle"},
        {"Autour des palombes", "Goshawk"},
        {"Grand rhinolophe", "GreaterHorseshoeBat"},
        {"Pic épeiche", "GreaterSpottedWoodpecker"},
        {"Grande sauterelle verte", "GreatGreenBushCricket"},
        {"Hérisson commun", "Hedgehog"},
        {"Marronnier commun", "HorseChestnut"},
        {"Grande tortue", "LargeTortoiseshell"},
        {"Tilleul", "Linden"},
        {"Lynx", "Lynx"},
        {"Carte géographique", "MapButterfly"},
        {"Taupe", "Mole"},
        {"Mousse", "Moss"},
        {"Lièvre variable", "MountainHare"},
        {"Rossignol philomèle", "Nightingale"},
        {"Coulemelle", "ParasolMushroom"},
        {"Paon-du-jour", "PeacockButterfly"},
        {"Cèpe de Bordeaux", "PennyBun"},
        {"Petit apollon", "PhoebusApollo"},
        {"Cistude", "PondTurtle"},
        {"Grand mars changeant", "PurpleEmperor"},
        {"Raton laveur", "Raccoon"},
        {"Cerf élaphe", "RedDeer"},
        {"Renard roux", "RedFox"},
        {"Écureuil roux", "RedSquirrel"},
        {"Chevreuil", "RoeDeer"},
        {"Vespère de Savi", "SavisPipistrelle"},
        {"Sapin blanc", "SilverFir"},
        {"Tabac d'Espagne", "SilverWashedFritillary"},
        {"Marcassin", "Squeaker"},
        {"Lucane", "StagBeetle"},
        {"Bouquetin des Alpes", "Steinbock"},
        {"Grande ortie", "StingingNettle"},
        {"Pin cembro", "StonePine"},
        {"Érable", "Sycamore"},
        {"Chouette hulotte", "TawnyOwl"},
        {"Fougère arborescente", "TreeFerns"},
        {"Rainette verte", "TreeFrog"},
        {"Xylocope violet", "VioletCarpenterBee"},
        {"Campagnol terrestre", "WaterVole"},
        {"Sanglier", "WildBoar"},
        {"Laie", "FemaleWildBoar"},
        {"Fraise des bois", "WildStrawberries"},
        {"Loup", "Wolf"},
        {"Fourmi rousse", "WoodAnt"},
        {"Pousse d'arbre", "Sapling"},
        {"Grand corbeau", "CommonRaven"},   };
}
